[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Piecewise = "f03ddd90-437e-4cf2-8f6c-e62f92609b90"
PiecewiseHilbert = "fb75a84c-a7ae-4011-94d8-abc4bb6dbff9"
PiecewiseLorentz = "5265c256-a0b7-4541-80b8-9bb011dcc609"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[sources]
Piecewise = {path = "../Piecewise/"}
PiecewiseHilbert = {path = "../PiecewiseHilbert/"}
PiecewiseLorentz = {path = "../PiecewiseLorentz/"}

[compat]
Documenter = "1.8"
#Plots = "1.40.9"
