name: Build JOSS paper draft

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: TeX and PDF
        uses: docker://openjournals/paperdraft:latest
        with:
          args: '-k joss/paper.md'
        env:
          GIT_SHA: $GITHUB_SHA
          JOURNAL: joss
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: joss/
