name = "PiecewiseHilbert"
uuid = "fb75a84c-a7ae-4011-94d8-abc4bb6dbff9"
authors = ["Christophe Berthod <christophe.berthod@unige.ch>"]
version = "0.1.1"

[deps]
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
Piecewise = "f03ddd90-437e-4cf2-8f6c-e62f92609b90"
PolyLog = "85e3b03c-9856-11eb-0374-4dc1f8670e7f"

[compat]
HypergeometricFunctions = "0.3.27"
Piecewise = "0.1.0"
PolyLog = "2.5.1"
Test = "1.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
